"""Pure-spectral (frequency-domain) models for the M6 campaign.

The inverse disturbance operator d = M qdd - B u is exactly frequency-
independent (LTI), so a single complex-linear map shared across rfft bins
is the exactly-right model class (26 complex parameters).  A fixed
whitening matrix W = C^{-1/2} of the per-pair joint train Gram makes the
probed input subspace near-identity so first-order SGD converges on the
quadratic (the S5a recipe reached official test rl2 2.89e-6).

Semantics are verbatim from the validated spike implementation
experiments/analysis/2026-08-24/m6_spike_spectral.py: SpectralSharedMap
forward einsums "bki,ij->bkj" (whitening) and "bki,oi->bko" (map) with
irfft back to the input length, complex128 throughout; GridAdapter casts
inputs to float64 when the map parameter is cdouble.  ``W`` is a
persistent buffer so it round-trips through checkpoint state_dicts under
evaluate.py's strict load protocol; ``whiten_path`` must exist at
construction time (generated by scripts/analysis/spectral_whiten.py).
"""

from __future__ import annotations

from pathlib import Path

import torch
import torch.nn as nn

PathLike = str | Path


class SpectralMap(nn.Module):
    """Direct complex-linear map: ONE (out, in) matrix shared across all bins.

    forward(x): rfft -> whitening -> M -> irfft, float64/complex128 end to
    end.  The parameter M is complex128, initialized with scale
    1/in_channels (same scheme as the spike).
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        whiten_path: PathLike,
    ) -> None:
        super().__init__()
        scale = 1.0 / in_channels
        self.M = nn.Parameter(
            scale * torch.rand(out_channels, in_channels, dtype=torch.cdouble)
        )
        w = torch.load(whiten_path, map_location="cpu", weights_only=True)
        self.register_buffer("W", w.detach().clone(), persistent=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:  # (B, 501, 13) -> (B, 501, 2)
        xft = torch.fft.rfft(x, dim=1)  # (B, 251, 13) complex
        xft = torch.einsum("bki,ij->bkj", xft, self.W.to(xft.dtype))
        out_ft = torch.einsum("bki,oi->bko", xft, self.M)  # (B, 251, 2)
        return torch.fft.irfft(out_ft, n=x.shape[1], dim=1)


class GridAdapter(nn.Module):
    """map (inputs, grid) -> model(inputs), matching the trainer/evaluate call.

    Casts inputs to the model's dtype (float64 when the spectral map is
    complex128), so official-metric evaluation matches the trained dtype.
    The grid argument is ignored.
    """

    def __init__(self, model: nn.Module) -> None:
        super().__init__()
        self.model = model
        parameter = next(model.parameters())
        self.in_dtype = (
            torch.float64 if parameter.dtype == torch.cdouble else torch.float32
        )

    def forward(self, inputs: torch.Tensor, grid: torch.Tensor) -> torch.Tensor:
        return self.model(inputs.to(self.in_dtype))
